### ISSUE TITLE
compatibility with HTML Snippets

### ISSUE THREAD

**Issue by dvic** [stefanjarina/vscode-eex-snippets#3]
Is it possible to get this plugin to also provide snippets for regular HTML elements? (`p`, `head`, etc.)

**Comment by dvic** [comment]
I figured it out, just add this to your settings: 

```
"emmet.includeLanguages": { 
    "HTML (EEx)": "html" 
  },
```

**Comment by stefanjarina** [comment]
Hi @dvic 
I'm glad that you found a solution.
It is indeed a correct approach as Emmet has quite complex functionality which is impossible to recreate with just snippets :-)
