### ISSUE TITLE
Problems with HTML snippets

### ISSUE THREAD

**Issue by abmBispo** [stefanjarina/vscode-eex-snippets#6]
Hi there, Alan here.

I'm having troubles when I try to get both HTML snippets and EEx snippets at the same time in VS Code (**1.47.0**). When I active HTML language mode I have only access to HTML snippets, the same for EEx. It means I can't get snippets for both - for example - `div` and `e=` together. I'm the one who didn't understand how to get it running or it's not actually possible?

Thanks in advance.

**Comment by stefanjarina** [comment]
Hi there,

assuming the file name ends with  `.html.eex`. It will be correctly recognized as one of the Elixirs lang identifiers (now this greatly depends on your other extensions installed so I will list settings that will cover all.

Then setup your Emmet extension so it will also be triggered on eex language.

```json
  /********** EMMET ***********/
  "emmet.includeLanguages": {
    "HTML (EEx)": "html", // Older lang identifier, maybe not needed anymore
    "EEx": "html",        // Older lang identifier, maybe not needed anymore
    "HTML (Eex)": "html", // Older lang identifier, maybe not needed anymore
    "Eex": "html",        // Older lang identifier, maybe not needed anymore
    "html-eex": "html",
    "eex": "html",
    "javascript": "javascriptreact"
  },
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html",
    "HTML (EEx)": "html", // Older lang identifier, maybe not needed anymore
    "EEx": "html",        // Older lang identifier, maybe not needed anymore
    "HTML (Eex)": "html", // Older lang identifier, maybe not needed anymore
    "Eex": "html",        // Older lang identifier, maybe not needed anymore
    "html-eex": "html",
    "eex": "html"
  },
```

Not sure if you have to have it in both `emmet.includeLanguages` and `emmet.syntaxProfiles` though, so you can play with this to fit your PC.

Cheers,
S.

**Comment by stefanjarina** [comment]
As there is no response I assume this have helped, if not, please let me know. closing.

**Comment by abmBispo** [comment]
Sorry about delay. Yes, this Emmet configuration you posted is working perfectly on VScode. for both HTML and EEx snippets. Great work here!
